[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "google-auth>=2.40.3",
    "gspread>=6.2.1",
    "requests>=2.32.4",
    "telegram>=0.0.1",
]
